UPDATE `gaz_config` SET `cvalue` = '157' WHERE `id` =2;
CREATE TABLE IF NOT EXISTS `gaz_forme_giuridiche` (
  `id_forgiu` int(10) NOT NULL AUTO_INCREMENT,
  `descri` varchar(100) DEFAULT NULL,
  `sigla` varchar(15) DEFAULT NULL,
  `ordine` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`id_forgiu`),
  KEY `ordine` (`ordine`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=73;
INSERT INTO `gaz_forme_giuridiche` (`id_forgiu`, `descri`, `sigla`, `ordine`) VALUES
	(1, 'ASSOCIAZIONE IMPRESA', 'ASS.IMP', 1),
	(2, 'ASSOCIAZIONE IN PARTECIPAZIONE', 'ASS.PART.', NULL),
	(3, 'AZIENDA AUTONOMA STATALE', 'AZ.AU.STAT', 1),
	(4, 'AZIENDA MUNICIPALE', 'AZ.MUNIP', 1),
	(5, 'AZIENDA PROVINCIALE', 'AZ.PROV', 1),
	(6, 'AZIENDA REGIONALE', 'AZ.REG', 1),
	(7, 'AZIENDA SPECIALE', 'AZ.SPEC', 1),
	(8, 'AZIENDA SPECIALE DI CUI AL DLGS 267/2000', 'AZ.SP267', NULL),
	(9, 'AZIENDA SPECIALE DI ENTE LOCALE', 'AZ.SP.ENTE', 1),
	(10, 'CONSORZIO FIDI', 'CONS.FIDI', NULL),
	(11, 'ENTE', 'ENTE', NULL),
	(12, 'ENTE DI CUI ALLA L.R. 21-12-93 N.88', 'ENTE88', NULL),
	(13, 'ENTE DIRITTO PUBBLICO', 'ENTEDIRPUB', NULL),
	(14, 'ENTE ECCLESIASTICO', 'ENTEECCL', NULL),
	(15, 'ENTE ECCLESIASTICO CIVILMENTE RICONOSCIUTO', 'ENTEECCLCR', NULL),
	(16, 'ENTE IMPRESA', 'ENTEIMP', NULL),
	(17, 'ENTE MORALE', 'ENTEMOR', NULL),
	(18, 'ENTE PUBBLICO COMMERCIALE', 'ENTEPUBCOM', NULL),
	(19, 'ENTE PUBBLICO ECONOMICO', 'ENTEPUBECO', NULL),
	(20, 'ENTE SOCIALE', 'ENTESOC', NULL),
	(21, 'FONDAZIONE', 'FOND', NULL),
	(22, 'FONDAZIONE IMPRESA', 'FONDIMP', NULL),
	(23, 'GRUPPO EUROPEO DI INTERESSE ECONOMICO', 'GEIE', NULL),
	(24, 'ISTITUTO DI CREDITO', 'ISTCRED', 1),
	(25, 'ISTITUTO DI CREDITO DI DIRITTO PUBBLICO', 'ISTCREDPUB', NULL),
	(26, 'ISTITUTO RELIGIOSO', 'ISTRELIG', NULL),
	(27, 'MUTUA ASSICURAZIONE', 'MUTUASS', NULL),
	(28, 'SOCIETA\' ANONIMA', 'SOC.ANON', NULL),
	(29, 'SOCIETA\' CONSORTILE', 'SOC.CONS', NULL),
	(30, 'SOCIETA\' CONSORTILE A RESPONSABILITA\' LIMITATA', 'SOC.CONS.R', NULL),
	(31, 'SOCIETA\' CONSORTILE IN ACCOMANDITA SEMPLICE', 'SOC.CONS.A', NULL),
	(32, 'SOCIETA\' CONSORTILE IN NOME COLLETTIVO', 'SOC.CONS.N', NULL),
	(33, 'SOCIETA\' CONSORTILE PER AZIONI', 'SOC.CONS.P', NULL),
	(34, 'SOCIETA\' COSTITUITA IN BASE A LEGGI DI ALTRO STATO', 'SOC.ESTERA', NULL),
	(35, 'SOCIETA\' DI MUTUO SOCCORSO', 'SOC.MUT.SO', NULL),
	(36, 'SOCIETA\' NON PREVISTA DALLA LEGISLAZIONE ITALIANA', 'SOC.NOLEGG', NULL),
	(37, 'SOGGETTO ESTERO', 'SOG.ESTERO', NULL),
	(38, 'CONSORZIO', 'CONS', NULL),
	(39, 'CONSORZIO CON ATTIVITA\' ESTERNA', 'CONS.ATT.E', NULL),
	(40, 'CONSORZIO DI CUI AL DLGS 267/2000', 'CONS.267', NULL),
	(41, 'CONSORZIO INTERCOMUNALE', 'CONS.INTCO', NULL),
	(42, 'CONSORZIO MUNICIPALE', 'CONS.MUNI', NULL),
	(43, 'CONSORZIO SENZA ATTIVITA\' ESTERNA', 'CON.S.AT.E', NULL),
	(44, 'CONTRATTO DI RETE DOTATO DI SOGGETTIVITA\' GIURIDICA', 'RETEGIUR', NULL),
	(45, 'COOPERATIVA SOCIALE', 'COOP.SOC', 1),
	(46, 'PICCOLA SOCIETA\' COOPERATIVA', 'P.SOC.COOP', NULL),
	(47, 'PICCOLA SOCIETA\' COOPERATIVA A RESPONSABILITA\' LIMITATA', 'P.SOC.COOP.RL', NULL),
	(48, 'SOCIETA\' CONSORTILE COOPERATIVA A RESPONSABILITA\' LIMITATA', 'S.CONS.COOP.RL', NULL),
	(49, 'SOCIETA\' COOPERATIVA', 'SOC.COOP.', 1),
	(50, 'SOCIETA\' COOPERATIVA A RESPONSABILITA ILLIMITATA', 'SOC.COOP.ILL', NULL),
	(51, 'SOCIETA\' COOPERATIVA A RESPONSABILITA LIMITATA', 'SOC.COOP.RL', NULL),
	(52, 'SOCIETA\' COOPERATIVA CONSORTILE', 'SOC.COOP.CONS', NULL),
	(53, 'SOCIETA\' COOPERATIVA EUROPEA', 'SOC.COOP.EU', NULL),
	(54, 'IMPRESA FAMILIARE', 'IMP.FAMIL', NULL),
	(55, 'PERSONA FISICA', 'P.F.', 0),
	(56, 'SOCIETA\' DI CAPITALE', 'SOC.CAPITAL', NULL),
	(57, 'SOCIETA\' PER AZIONI CON SOCIO UNICO', 'SPA SOC.UNI', NULL),
	(58, 'SOCIETA\' A RESPONSABILITA\' LIMITATA', 'SRL', NULL),
	(59, 'SOCIETA\' A RESPONSABILITA\' LIMITATA A CAPITALE RIDOTTO', 'SRL CAP.RID', NULL),
	(60, 'SOCIETA\' A RESPONSABILITA\' LIMITATA CON UNICO SOCIO', 'SRL SOC.UNI', NULL),
	(61, 'SOCIETA\' A RESPONSABILITA\' LIMITATA SEMPLIFICATA', 'SRLS', NULL),
	(62, 'SOCIETA\' EUROPEA', 'SOC.EU', NULL),
	(63, 'SOCIETA\' IN ACCOMANDITA PER AZIONI', 'SAPA', 1),
	(64, 'SOCIETA\' PER AZIONI', 'SPA', 1),
	(65, 'COMUNIONE EREDITARIA', 'COM.EREDIT', NULL),
	(66, 'SOCIETA\' DI FATTO', 'SDF', 1),
	(67, 'SOCIETA\' IN ACCOMANDITA SEMPLICE', 'SAS', 1),
	(68, 'SOCIETA\' IN NOME COLLETTIVO', 'SNC', 1),
	(69, 'SOCIETA\' IRREGOLARE', 'SOC.IRREG', NULL),
	(70, 'SOCIETA\' SEMPLICE', 'S.S.', 1),
	(71, 'SOCIETA\' TRA PROFESSIONISTI', 'SOC.PROF.', 1),
	(72, 'NON SPECIFICATA', '', 1);
ALTER TABLE `gaz_anagra` CHANGE COLUMN `legrap_pf_nome` `legrap_pf_nome` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'nome del rappresentante legale (persona fisica)' AFTER `sedleg`, CHANGE COLUMN `legrap_pf_cognome` `legrap_pf_cognome` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'cognome del rappresentante legale (persona fisica)' AFTER `legrap_pf_nome`, ADD COLUMN `legrap_pf_luonas` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'luogo di nascita del rappresentante legale (persona fisica) ' AFTER `legrap_pf_cognome`, ADD COLUMN `legrap_pf_pronas` VARCHAR(2) NOT NULL DEFAULT '' COMMENT 'provincia di nascita del rappresentante legale (persona fisica) EE per esterno' AFTER `legrap_pf_luonas`, ADD COLUMN `legrap_pf_datnas` DATE NULL COMMENT 'data di nascita del rappresentante legale (persona fisica)' AFTER `legrap_pf_pronas`, ADD COLUMN `legrap_pf_codfis` VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'codice fiscale del rappresentante legale (persona fisica)' AFTER `legrap_pf_datnas`, ADD COLUMN `cod_ateco` INT(10) NULL DEFAULT NULL AFTER `pariva`, ADD COLUMN `id_forgiu` INT(10) NULL DEFAULT NULL COMMENT 'riferimento alla tabella gaz_forme_giuridiche' AFTER `sexper`;
-- START_WHILE ( questo e' un tag che serve per istruire install.php ad INIZIARE ad eseguire le query seguenti su tutte le aziende dell'installazione)
CREATE TABLE IF NOT EXISTS `gaz_XXXpagame_distribution` (
  `id_pagdis` int NOT NULL AUTO_INCREMENT,
  `codpag` int NOT NULL DEFAULT '0' COMMENT 'Referenza alla tabella gaz_XXXpagame (molti a uno)',
  `descri` varchar(50) NOT NULL DEFAULT '' COMMENT 'La descrizione è indispensabile in assenza di data di scadenza (expiry)',
  `ratperc` decimal(4,1) NOT NULL DEFAULT (0) COMMENT 'La somma dei righi riferiti allo stesso codpag dovrebbe essere 100 se non lo è viene troncato o riempito fino a capienza',
  `from_prev` varchar(3) NULL DEFAULT NULL COMMENT 'Sono i giorni  dalla scadenza precedente o dalla data di riferimento, si può indicare anche una lettere coma nella colonna tiprat di gaz_XXXpagame. non è indispensabile e se variabile, ovvero non strettamente determinato, es. quando il limite temporale dipende dalla fine dei lavori o da altre condizione queste verranno indicate in descrizione e lasciata vuota o NULL.',
  `tippag` char(1) NOT NULL DEFAULT '0' COMMENT 'La stessa della colonna tippag di gaz_XXXpagame ma prevale su di essa se valorizzata. Consente metodi di pagamento diversi sulle diverse rate',
  `fae_mode` varchar(4) DEFAULT NULL COMMENT 'Come su gaz_XXXpagame è il valore MPXX della fattura elettronica. Consente metodi di pagamento diversi sulle diverse rate',
  `id_bank` int NOT NULL,
  `annota` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_pagdis`) USING BTREE,
  KEY `codpag` (`codpag`),
  KEY `from_prev` (`from_prev`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Il contenuto di questa tabella serve per gestire i pagamenti con scadenze e rate non costanti nell''importo e nella periodicità. Ed è legata alla tabella gaz_XXXpagame. Ogni rigo di questa tabella rappresenta una rata per il pagamento riferito con la colonna codpag e verranno passate come matrice alla funzione CalcExpiry nel file expiry_calc.php ';
ALTER TABLE `gaz_XXXpagame` CHANGE COLUMN `tippag` `tippag` CHAR(1) NOT NULL DEFAULT '' COMMENT 'C=contanti,O=bonifico,K=carte di pagamento,D=rimessa diretta,I=rapporto interbancario diretto (RID),B=Ricevuta Bancaria,T=Cambiale-Tratta,V=mediante avviso(MAV),F=finanziamento,M=misto. ATTENZIONE se F o M ci si può appoggiare alla tabella gaz_XXXcompany_data per contenere dati quali anticipo, finanziato, importo rate, numero rate, periodicità' AFTER `descri`;
ALTER TABLE `gaz_XXXcompany_data`	COMMENT='Multipurpose table. Tabella per contenere dati di qualsiasi genere, utilizzabile sulle personalizzazioni per conservare (ad es.) documenti crittografati.', ADD COLUMN `id_ref` INT(10) NULL COMMENT 'Referenza numerica alla fonte' AFTER `id`,	ADD INDEX `id_ref` (`id_ref`);
-- STOP_WHILE ( questo e' un tag che serve per istruire install.php a SMETTERE di eseguire le query su tutte le aziende dell'installazione )
