UPDATE `gaz_config` SET `cvalue` = '157' WHERE `id` =2;
CREATE TABLE IF NOT EXISTS `gaz_forme_giuridiche` (
  `id_forgiu` int(10) NOT NULL AUTO_INCREMENT,
  `descri` varchar(100) DEFAULT NULL,
  `sigla` varchar(15) DEFAULT NULL,
  `ordine` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`id_forgiu`),
  KEY `ordine` (`ordine`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=73;
INSERT INTO `gaz_forme_giuridiche` (`id_forgiu`, `descri`, `sigla`, `ordine`) VALUES
	(1, 'ASSOCIAZIONE IMPRESA', 'ASS.IMP', 1),
	(2, 'ASSOCIAZIONE IN PARTECIPAZIONE', 'ASS.PART.', NULL),
	(3, 'AZIENDA AUTONOMA STATALE', 'AZ.AU.STAT', 1),
	(4, 'AZIENDA MUNICIPALE', 'AZ.MUNIP', 1),
	(5, 'AZIENDA PROVINCIALE', 'AZ.PROV', 1),
	(6, 'AZIENDA REGIONALE', 'AZ.REG', 1),
	(7, 'AZIENDA SPECIALE', 'AZ.SPEC', 1),
	(8, 'AZIENDA SPECIALE DI CUI AL DLGS 267/2000', 'AZ.SP267', NULL),
	(9, 'AZIENDA SPECIALE DI ENTE LOCALE', 'AZ.SP.ENTE', 1),
	(10, 'CONSORZIO FIDI', 'CONS.FIDI', NULL),
	(11, 'ENTE', 'ENTE', NULL),
	(12, 'ENTE DI CUI ALLA L.R. 21-12-93 N.88', 'ENTE88', NULL),
	(13, 'ENTE DIRITTO PUBBLICO', 'ENTEDIRPUB', NULL),
	(14, 'ENTE ECCLESIASTICO', 'ENTEECCL', NULL),
	(15, 'ENTE ECCLESIASTICO CIVILMENTE RICONOSCIUTO', 'ENTEECCLCR', NULL),
	(16, 'ENTE IMPRESA', 'ENTEIMP', NULL),
	(17, 'ENTE MORALE', 'ENTEMOR', NULL),
	(18, 'ENTE PUBBLICO COMMERCIALE', 'ENTEPUBCOM', NULL),
	(19, 'ENTE PUBBLICO ECONOMICO', 'ENTEPUBECO', NULL),
	(20, 'ENTE SOCIALE', 'ENTESOC', NULL),
	(21, 'FONDAZIONE', 'FOND', NULL),
	(22, 'FONDAZIONE IMPRESA', 'FONDIMP', NULL),
	(23, 'GRUPPO EUROPEO DI INTERESSE ECONOMICO', 'GEIE', NULL),
	(24, 'ISTITUTO DI CREDITO', 'ISTCRED', 1),
	(25, 'ISTITUTO DI CREDITO DI DIRITTO PUBBLICO', 'ISTCREDPUB', NULL),
	(26, 'ISTITUTO RELIGIOSO', 'ISTRELIG', NULL),
	(27, 'MUTUA ASSICURAZIONE', 'MUTUASS', NULL),
	(28, 'SOCIETA\' ANONIMA', 'SOC.ANON', NULL),
	(29, 'SOCIETA\' CONSORTILE', 'SOC.CONS', NULL),
	(30, 'SOCIETA\' CONSORTILE A RESPONSABILITA\' LIMITATA', 'SOC.CONS.R', NULL),
	(31, 'SOCIETA\' CONSORTILE IN ACCOMANDITA SEMPLICE', 'SOC.CONS.A', NULL),
	(32, 'SOCIETA\' CONSORTILE IN NOME COLLETTIVO', 'SOC.CONS.N', NULL),
	(33, 'SOCIETA\' CONSORTILE PER AZIONI', 'SOC.CONS.P', NULL),
	(34, 'SOCIETA\' COSTITUITA IN BASE A LEGGI DI ALTRO STATO', 'SOC.ESTERA', NULL),
	(35, 'SOCIETA\' DI MUTUO SOCCORSO', 'SOC.MUT.SO', NULL),
	(36, 'SOCIETA\' NON PREVISTA DALLA LEGISLAZIONE ITALIANA', 'SOC.NOLEGG', NULL),
	(37, 'SOGGETTO ESTERO', 'SOG.ESTERO', NULL),
	(38, 'CONSORZIO', 'CONS', NULL),
	(39, 'CONSORZIO CON ATTIVITA\' ESTERNA', 'CONS.ATT.E', NULL),
	(40, 'CONSORZIO DI CUI AL DLGS 267/2000', 'CONS.267', NULL),
	(41, 'CONSORZIO INTERCOMUNALE', 'CONS.INTCO', NULL),
	(42, 'CONSORZIO MUNICIPALE', 'CONS.MUNI', NULL),
	(43, 'CONSORZIO SENZA ATTIVITA\' ESTERNA', 'CON.S.AT.E', NULL),
	(44, 'CONTRATTO DI RETE DOTATO DI SOGGETTIVITA\' GIURIDICA', 'RETEGIUR', NULL),
	(45, 'COOPERATIVA SOCIALE', 'COOP.SOC', 1),
	(46, 'PICCOLA SOCIETA\' COOPERATIVA', 'P.SOC.COOP', NULL),
	(47, 'PICCOLA SOCIETA\' COOPERATIVA A RESPONSABILITA\' LIMITATA', 'P.SOC.COOP.RL', NULL),
	(48, 'SOCIETA\' CONSORTILE COOPERATIVA A RESPONSABILITA\' LIMITATA', 'S.CONS.COOP.RL', NULL),
	(49, 'SOCIETA\' COOPERATIVA', 'SOC.COOP.', 1),
	(50, 'SOCIETA\' COOPERATIVA A RESPONSABILITA ILLIMITATA', 'SOC.COOP.ILL', NULL),
	(51, 'SOCIETA\' COOPERATIVA A RESPONSABILITA LIMITATA', 'SOC.COOP.RL', NULL),
	(52, 'SOCIETA\' COOPERATIVA CONSORTILE', 'SOC.COOP.CONS', NULL),
	(53, 'SOCIETA\' COOPERATIVA EUROPEA', 'SOC.COOP.EU', NULL),
	(54, 'IMPRESA FAMILIARE', 'IMP.FAMIL', NULL),
	(55, 'PERSONA FISICA', 'P.F.', 0),
	(56, 'SOCIETA\' DI CAPITALE', 'SOC.CAPITAL', NULL),
	(57, 'SOCIETA\' PER AZIONI CON SOCIO UNICO', 'SPA SOC.UNI', NULL),
	(58, 'SOCIETA\' A RESPONSABILITA\' LIMITATA', 'SRL', NULL),
	(59, 'SOCIETA\' A RESPONSABILITA\' LIMITATA A CAPITALE RIDOTTO', 'SRL CAP.RID', NULL),
	(60, 'SOCIETA\' A RESPONSABILITA\' LIMITATA CON UNICO SOCIO', 'SRL SOC.UNI', NULL),
	(61, 'SOCIETA\' A RESPONSABILITA\' LIMITATA SEMPLIFICATA', 'SRLS', NULL),
	(62, 'SOCIETA\' EUROPEA', 'SOC.EU', NULL),
	(63, 'SOCIETA\' IN ACCOMANDITA PER AZIONI', 'SAPA', 1),
	(64, 'SOCIETA\' PER AZIONI', 'SPA', 1),
	(65, 'COMUNIONE EREDITARIA', 'COM.EREDIT', NULL),
	(66, 'SOCIETA\' DI FATTO', 'SDF', 1),
	(67, 'SOCIETA\' IN ACCOMANDITA SEMPLICE', 'SAS', 1),
	(68, 'SOCIETA\' IN NOME COLLETTIVO', 'SNC', 1),
	(69, 'SOCIETA\' IRREGOLARE', 'SOC.IRREG', NULL),
	(70, 'SOCIETA\' SEMPLICE', 'S.S.', 1),
	(71, 'SOCIETA\' TRA PROFESSIONISTI', 'SOC.PROF.', 1),
	(72, 'NON SPECIFICATA', '', 1);
ALTER TABLE `gaz_anagra` CHANGE COLUMN `legrap_pf_nome` `legrap_pf_nome` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'nome del rappresentante legale (persona fisica)' AFTER `sedleg`, CHANGE COLUMN `legrap_pf_cognome` `legrap_pf_cognome` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'cognome del rappresentante legale (persona fisica)' AFTER `legrap_pf_nome`, ADD COLUMN `legrap_pf_luonas` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'luogo di nascita del rappresentante legale (persona fisica) ' AFTER `legrap_pf_cognome`, ADD COLUMN `legrap_pf_pronas` VARCHAR(2) NOT NULL DEFAULT '' COMMENT 'provincia di nascita del rappresentante legale (persona fisica) EE per esterno' AFTER `legrap_pf_luonas`, ADD COLUMN `legrap_pf_datnas` DATE NULL COMMENT 'data di nascita del rappresentante legale (persona fisica)' AFTER `legrap_pf_pronas`, ADD COLUMN `legrap_pf_codfis` VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'codice fiscale del rappresentante legale (persona fisica)' AFTER `legrap_pf_datnas`, ADD COLUMN `cod_ateco` INT(10) NULL DEFAULT NULL AFTER `pariva`, ADD COLUMN `id_forgiu` INT(10) NULL DEFAULT NULL COMMENT 'riferimento alla tabella gaz_forme_giuridiche' AFTER `sexper`;
DROP TABLE IF EXISTS `gaz_biochemical_parameters`;
CREATE TABLE IF NOT EXISTS `gaz_biochemical_parameters` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Parte` varchar(10) DEFAULT NULL,
  `Parametro` varchar(38) DEFAULT NULL,
  `ValMassimoParametro` varchar(56) DEFAULT NULL,
  `ValMinimoParametro` varchar(56) DEFAULT NULL,
  `Unità di misura` varchar(30) DEFAULT NULL,
  `Note` varchar(1332) DEFAULT NULL,
  `RiferimentoNormativo` varchar(127) DEFAULT NULL,
  `Metodo` varchar(255) DEFAULT NULL,
  `Settore` varchar(63) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Parametro` (`Parametro`),
  KEY `Parte` (`Parte`)
) ENGINE=MyISAM AUTO_INCREMENT=63;
INSERT INTO `gaz_biochemical_parameters` (`id`, `Parte`, `Parametro`, `ValMassimoParametro`, `ValMinimoParametro`, `Unità di misura`, `Note`, `RiferimentoNormativo`, `Metodo`, `Settore`) VALUES
(1, 'A', 'Enterococchi intestinali', '0', NULL, 'numero/100 ml', 'Per le acque confezionate in bottiglie o contenitori, l’unità di misura è «numero/250 ml»', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(2, 'A', 'Escherichia coli (E. coli)', '0', NULL, 'numero/100 ml', 'Per le acque confezionate in bottiglie o contenitori, l’unità di misura è «numero/250 ml»', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(3, 'B', 'Antimonio', '10', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(4, 'B', 'Arsenico', '10', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(5, 'B', 'Benzene', '1', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(6, 'B', 'Benzo(a)pirene', '0.01', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(7, 'B', 'Bisfenolo A', '2.5', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(8, 'B', 'Boro', '1.5', NULL, 'mg/l', 'Il valore di parametro di 2,4 mg/l si applica qualora l’acqua desalinizzata sia la principale fonte del sistema di fornitura in questione o in regioni in cui le condizioni geologiche potrebbero causare livelli elevati di boro nelle acque sotterranee.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(9, 'B', 'Bromato', '10', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(10, 'B', 'Cadmio', '5', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(11, 'B', 'Clorato', '0.25', NULL, 'mg/l', 'Nei casi in cui il metodo di disinfezione usato non generi clorato, il valore di parametro di 0,25 mg/l deve essere soddisfatto al più tardi il 12 gennaio 2026. Nei casi in cui per la disinfezione si utilizza un metodo di disinfezione che genera clorato, in particolare diossido di cloro, si applica il valore di parametro di 0,70 mg/l. Ove possibile, i gestori idro-potabili si adoperano per applicare valori inferiori senza compromettere la disinfezione. Questo parametro è misurato esclusivamente se si utilizzano i metodi di disinfezione in questione.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(12, 'B', 'Clorito', '0.25', NULL, 'mg/l', 'Nei casi in cui il metodo di disinfezione usato non generi clorito, il valore di parametro di 0,25 mg/l deve essere soddisfatto al più tardi il 12 gennaio 2026; fino al 11 gennaio 2026 il valore di parametro del clorito è pari a 0,7 mg/l. Nei casi in cui per la disinfezione si utilizza un metodo di disinfezione che genera clorito, in particolare diossido di cloro, si applica il valore di parametro di 0,70 mg/l. Ove possibile, i gestori idro-potabili si adoperano per applicare valori inferiori senza compromettere la disinfezione. Questo parametro è misurato esclusivamente se si utilizzano i metodi di disinfezione in', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(13, 'B', 'Cromo', '25', NULL, 'µg/l', 'Il valore di parametro del cromo deve essere soddisfatto al più tardi il 12 gennaio 2026. Il valore di parametro del cromo fino al 11 gennaio 2026 è pari a 50 µg/l. Le regioni e province autonome, le Aziende sanitarie locali ed i gestori idro-potabili, ciascuno per quanto di competenza, devono provvedere affinché venga ridotta al massimo la concentrazione di cromo nelle acque destinate al consumo umano durante il suddetto periodo di transizione, per conformarsi al nuovo valore di parametro. Nell\'attuazione delle misure intese a garantire il raggiungimento del valore in questione deve darsi gradualmente priorità ai punti in cui la concentrazione di cromo nelle acque destinate al consumo umano è più elevata e l\'origine non è geogenica.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(14, 'B', 'Rame', '2', NULL, 'mg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(15, 'B', 'Cianuro', '50', NULL, 'µg/l', 'Si considera il parametro cianuri totali.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(16, 'B', '1,2-dicloroetano', '3', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(17, 'B', 'Epicloridrina', '0.1', NULL, 'µg/l', 'Il valore di parametro di 0,10 µg/l si riferisce alla concentrazione monomerica residua nell’acqua calcolata a partire dal valore massimo della migrazione specifica desumibile dalle specifiche tecniche del corrispondente polimero a contatto con l’acqua, nei casi in cui detto polimero sia utilizzato nella filiera idro-potabile.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(18, 'B', 'Fluoruro', '1.5', NULL, 'mg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(19, 'B', 'Acidi aloacetici (HAAs)', '60', NULL, 'µg/l', 'Questo parametro è misurato esclusivamente se per la disinfezione delle acque destinate al consumo umano si utilizzano metodi di disinfezione suscettibili di generare acidi aloacetici. Esso è la somma delle seguenti cinque sostanze rappresentative: acido monocloro-, dicloro-, e tricloro-acetico, acido mono- e dibromo-acetico.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(20, 'B', 'Piombo', '5', NULL, 'µg/l', 'Il valore di parametro di 5,0 µg/l deve essere soddisfatto al più tardi entro il 12 gennaio 2036. Il valore di parametro per il piombo fino a tale data è 10 µg/l. Dopo tale data, il valore di parametro di 5,0 µg/l deve essere soddisfatto al punto di consegna.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(21, 'B', 'Mercurio', '1', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(22, 'B', 'Microcistina-LR', '1', NULL, 'µg/l', 'È necessario che questo parametro sia misurato esclusivamente in caso di potenziali fioriture algali (crescita massiva di cellule cianobatteriche o potenziale formazione di efflorescenze) nell’acqua da destinare a consumo umano, secondo i criteri definiti nelle Linee guida per la gestione del rischio cianobatteri in acque destinate a consumo umano, Rapporti ISTISAN 11/35 Pt. 2 e s.m.i.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(23, 'B', 'Nichel', '20', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(24, 'B', 'Nitrato', '50', NULL, 'mg/l', 'Deve essere soddisfatta la condizione: (Cnitrato/VPnitrato + Cnitrito/VPnitrito) ≤ 1 ove C e VP rappresentano, rispettivamente, la concentrazione in mg/l e il corrispondente valore di parametro per nitrato e nitrito.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(25, 'B', 'Nitrito', '0.5', NULL, 'mg/l', 'Deve essere soddisfatta la condizione: (Cnitrato/VPnitrato + Cnitrito/VPnitrito) ≤ 1 ove C e VP rappresentano, rispettivamente, la concentrazione e il corrispondente valore di parametro per nitrato e nitrito. Per acque provenienti da impianti di trattamenti che possono generare lo ione nitrito – in particolare attraverso l’ossidazione dello ione ammonio, la riduzione dello ione nitrato o l’idrolisi delle cloroammine - si applica il valore di parametro di 0,10 mg/l al parametro nitrito.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(26, 'B', 'Antiparassitari', '0.1', NULL, 'µg/l', 'Per «antiparassitari» s’intende: insetticidi organici erbicidi organici fungicidi organici nematocidi organici acaricidi organici alghicidi organici rodenticidi organici slimicidi organici prodotti connessi (tra l’altro regolatori della crescita) e relativi metaboliti ai sensi dell’articolo 3, punto 32, del regolamento (CE) n. 1107/2009 del Parlamento europeo e del Consiglio ritenuti pertinenti per le acque destinate al consumo umano. Un metabolita di antiparassitari è considerato pertinente per le acque destinate al consumo umano se esistono motivi per ritenere che possieda proprietà intrinseche, comparabili a quelle della sostanza madre, in termini di attività antiparassitaria bersaglio o che generi (esso stesso o i suoi prodotti di trasformazione) un rischio per la salute dei consumatori. Il valore di 0,10 µg/l si applica ad ogni singolo antiparassitario. Nel caso di aldrina, dieldrina, eptacloro ed eptacloro epossido, il valore di parametro è pari a 0,030 µg/l. Il monitoraggio è necessario solo per gli antiparassitari di cui è probabile la presenza in un determinato sistema di fornitura. Sulla base dei dati comunicati dagli Stati membri, la Commissione può istituire una banca dati di antiparassitari e dei relativi metaboliti tenendo conto della loro possibile presenza nelle acque destinate al consumo umano.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(27, 'B', 'Antiparassitari -Totale', '0.5', NULL, 'µg/l', 'Per «antiparassitari — totale» si intende la somma di tutti i singoli antiparassitari sopra indicati, rilevati e quantificati nella procedura di monitoraggio.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(28, 'B', 'PFAS Totale', '0.5', NULL, 'µg/l', 'Per «PFAS — totale» si intende la totalità delle sostanze per- e polifluoroalchiliche. Tale valore di parametro si applica esclusivamente dopo l’elaborazione di orientamenti tecnici per il monitoraggio di tale parametro in conformità dell’articolo 12, comma 9. Le regioni e province autonome possono quindi decidere di utilizzare uno o entrambi i parametri «PFAS — totale» o «Somma di PFAS». L’Autorità sanitaria locale preposta al controllo della qualità delle acque destinate al consumo umano, sentita l’autorità sanitaria regionale e l’ISS, può adottare valori più restrittivi in specifiche circostanze territoriali, tenuto conto in particolare dell’esposizione pregressa alle sostanze per- e polifluoroalchiliche della popolazione interessata.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(29, 'B', 'Somma di PFAS', '0.1', NULL, 'µg/l', 'Per «somma di PFAS» si intende la somma di tutte le sostanze per- e polifluoroalchiliche ritenute preoccupanti per quanto riguarda le acque destinate al consumo umano di cui all’allegato III, Parte B, punto 3. Si tratta di un sottoinsieme di sostanze «PFAS — totale» contenenti un Gruppo perfluoroalchilico con tre o più atomi di carbonio (vale a dire –CnF2n–, n ≥ 3) o un Gruppo perfluoroalchiletere con due o più atomi di carbonio (vale a dire –CnF2nOCmF2m–, n e m ≥ 1). L’Autorità sanitaria locale preposta al controllo della qualità delle acque destinate al consumo umano, sentita l’autorità sanitaria regionale e l’ISS può adottare valori più restrittivi in specifiche circostanze territoriali, tenuto conto in particolare dell’esposizione pregressa alle sostanze per- e polifluoroalchiliche della popolazione interessata.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(30, 'B', 'Idrocarburi policiclici aromatici', '0.1', NULL, 'µg/l', 'Somma delle concentrazioni dei seguenti composti specifici: benzo(b) fluorantene, benzo(k)fluorantene, benzo(ghi)perilene e indeno(1,2,3- cd)pirene.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(31, 'B', 'Selenio', '20', NULL, 'µg/l', 'Il valore di parametro di 30 µg/l si applica per le regioni e province autonome in cui le condizioni geologiche potrebbero comportare livelli elevati di selenio nelle acque sotterranee.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(32, 'B', 'Tetracloroetilene e tricloroetilene', '10', NULL, 'µg/l', 'Somma delle concentrazioni di tali due parametri.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(33, 'B', 'Trialometani -Totale', '30', NULL, 'µg/l', 'Ove possibile, i gestori idro-potabili si adoperano per applicare valori di parametro inferiori senza compromettere la disinfezione. Essa è la somma delle concentrazioni dei seguenti composti specifici: cloroformio, bromoformio, dibromoclorometano, e bromodiclorometano.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(34, 'B', 'Uranio', '30', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(35, 'B', 'Vanadio', '140', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(36, 'B', 'Vinilcloruro', '0.5', NULL, 'µg/l', 'Il valore parametrico di 0,50 µg/l si riferisce alla concentrazione monomerica residua in acqua, calcolata a partire dal valore massimo della migrazione specifica desumibile dalle specifiche tecniche del corrispondente polimero a contatto con l’acqua, nei casi in cui detto polimero sia utilizzato nella filiera idro-potabile.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(37, 'C1', 'Alluminio', '200', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(38, 'C1', 'Ammonio', '0.5', NULL, 'mg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(39, 'C1', 'Cloruro', '250', NULL, 'mg/l', 'L’acqua non deve essere corrosiva.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(40, 'C1', 'Clostridium perfringens spore comprese', '0', NULL, 'Numero/100 ml', 'Questo parametro deve essere misurato se indicato come appropriato dalla valutazione del rischio.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(41, 'C1', 'Colore', 'Accettabile per i consumatori e senza variazioni anomale', NULL, '', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(42, 'C1', 'Conduttività', '2500', NULL, 'µS cm-1 a 20 °C', 'L’acqua non deve essere aggressiva.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(45, 'C1', 'Concentrazione ioni idrogeno', '9.5', '6.5', 'Unità pH', 'L’acqua non deve essere aggressiva. Per le acque non frizzanti confezionate in bottiglie o contenitori il valore minimo può essere ridotto a 4,5 unità pH. Per le acque naturalmente ricche di anidride carbonica o arricchite artificialmente, il valore minimo può essere inferiore.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(46, 'C1', 'Ferro', '200', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(47, 'C1', 'Manganese', '50', NULL, 'µg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(48, 'C1', 'Odore', 'Accettabile per i consumatori e senza variazioni anomale', NULL, '', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(49, 'C1', 'Ossidabilità', '5', NULL, 'mg/l O2', 'Se si analizza il parametro TOC non è necessario determinare questo parametro.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(50, 'C1', 'Solfato', '250', NULL, 'mg/l', 'L’acqua non deve essere corrosiva.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(51, 'C1', 'Sodio', '200', NULL, 'mg/l', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(52, 'C1', 'Sapore', 'Accettabile per i consumatori e senza variazioni anomale', NULL, '', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(53, 'C1', 'Conteggio delle colonie a 22 °C', 'Senza variazioni anomale', NULL, '', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(54, 'C1', 'Batteri coliformi', '0', NULL, 'Numero/100 ml', 'Per le acque confezionate in bottiglie o contenitori, l’unità di misura è «Numero/250 ml». Per la valutazione di rischio ai sensi dell’articolo 15, comma 1, lettera d, si rimanda alla Circolare del Ministero della salute 13400 del 1aprile 2021, e successive modifiche o integrazioni.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(55, 'C1', 'Carbonio organico totale (TOC)', 'Senza variazioni anomale', NULL, '', 'Non è necessario misurare questo parametro per forniture d’acqua inferiori a 10.000 m3 al giorno.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(56, 'C1', 'Torbidità', 'Accettabile per i consumatori e senza variazioni anomale', NULL, '', '', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(57, 'C2', 'Solidi disciolti totali', '', '100', 'mg/l', 'Il valore soglia deve essere assicurato mediante adeguata miscelazione con acque destinate a consumo umano di diversa origine o adeguati trattamenti di remineralizzazione.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(58, 'C2', 'Durezza totale', '', '15', '°F', 'Il valore soglia deve essere assicurato mediante adeguata miscelazione con acque destinate a consumo umano di diversa origine o adeguati trattamenti di remineralizzazione.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(59, 'C2', 'Calcio', '', '30', 'mg/l', 'Il valore soglia deve essere assicurato mediante adeguata miscelazione con acque destinate a consumo umano di diversa origine o adeguati trattamenti di remineralizzazione.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(60, 'C2', 'Magnesio', '', '10', 'mg/l', 'Il valore soglia deve essere assicurato mediante adeguata miscelazione con acque destinate a consumo umano di diversa origine o adeguati trattamenti di remineralizzazione.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(61, 'D', 'Legionella', '1000', NULL, 'unità formanti colonia (UFC)/l', 'Questo valore di parametro è definito ai fini degli articoli 9 e 14. Le azioni previste da tali articoli potrebbero essere prese in considerazione anche al di sotto del valore di parametro, in particolare in caso di infezioni e focolai. In questi casi va confermata la fonte dell’infezione e identificata la specie di Legionella.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO'),
(62, 'D', 'Piombo', '5', NULL, 'µg/l', 'Il valore di parametro è definito ai fini dell’articolo 9 e deve essere rispettato al punto di uso dei sistemi di distribuzione interni negli edifici, locali e navi. Il valore di parametro di 5,0 µg/l deve essere soddisfatto al più tardi entro il 12 gennaio 2036. Il valore di parametro per il piombo fino a tale data è 10 µg/l. I gestori dei sistemi di distribuzione interni devono adoperarsi affinché il valore più basso di 5,0 µg/l sia raggiunto il prima possibile, e comunque non oltre il 12 gennaio 2036.', 'DECRETO LEGISLATIVO n.18 del 23 febbraio 2023', NULL, 'ACQUE DESTINATE AL CONSUMO UMANO');
INSERT INTO `gaz_menu_module` SELECT  MAX(id)+1,(SELECT MIN(id) FROM `gaz_module` WHERE `name`='lims'), 'report_biochemical_parameters.php','', '', 2, '', 90 FROM `gaz_menu_module`;
-- START_WHILE ( questo e' un tag che serve per istruire install.php ad INIZIARE ad eseguire le query seguenti su tutte le aziende dell'installazione)
CREATE TABLE IF NOT EXISTS `gaz_XXXpagame_distribution` (
  `id_pagdis` int NOT NULL AUTO_INCREMENT,
  `codpag` int NOT NULL DEFAULT '0' COMMENT 'Referenza alla tabella gaz_XXXpagame (molti a uno)',
  `descri` varchar(50) NOT NULL DEFAULT '' COMMENT 'La descrizione è indispensabile in assenza di data di scadenza (expiry)',
  `ratperc` decimal(4,1) NOT NULL DEFAULT (0) COMMENT 'La somma dei righi riferiti allo stesso codpag dovrebbe essere 100 se non lo è viene troncato o riempito fino a capienza',
  `from_prev` varchar(3) NULL DEFAULT NULL COMMENT 'Sono i giorni  dalla scadenza precedente o dalla data di riferimento, si può indicare anche una lettere coma nella colonna tiprat di gaz_XXXpagame. non è indispensabile e se variabile, ovvero non strettamente determinato, es. quando il limite temporale dipende dalla fine dei lavori o da altre condizione queste verranno indicate in descrizione e lasciata vuota o NULL.',
  `tippag` char(1) NOT NULL DEFAULT '0' COMMENT 'La stessa della colonna tippag di gaz_XXXpagame ma prevale su di essa se valorizzata. Consente metodi di pagamento diversi sulle diverse rate',
  `fae_mode` varchar(4) DEFAULT NULL COMMENT 'Come su gaz_XXXpagame è il valore MPXX della fattura elettronica. Consente metodi di pagamento diversi sulle diverse rate',
  `id_bank` int NOT NULL,
  `annota` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_pagdis`) USING BTREE,
  KEY `codpag` (`codpag`),
  KEY `from_prev` (`from_prev`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Il contenuto di questa tabella serve per gestire i pagamenti con scadenze e rate non costanti nell''importo e nella periodicità. Ed è legata alla tabella gaz_XXXpagame. Ogni rigo di questa tabella rappresenta una rata per il pagamento riferito con la colonna codpag e verranno passate come matrice alla funzione CalcExpiry nel file expiry_calc.php ';
ALTER TABLE `gaz_XXXpagame` CHANGE COLUMN `tippag` `tippag` CHAR(1) NOT NULL DEFAULT '' COMMENT 'C=contanti,O=bonifico,K=carte di pagamento,D=rimessa diretta,I=rapporto interbancario diretto (RID),B=Ricevuta Bancaria,T=Cambiale-Tratta,V=mediante avviso(MAV),F=finanziamento,M=misto. ATTENZIONE se F o M ci si può appoggiare alla tabella gaz_XXXcompany_data per contenere dati quali anticipo, finanziato, importo rate, numero rate, periodicità' AFTER `descri`;
ALTER TABLE `gaz_XXXcompany_data`	COMMENT='Multipurpose table. Tabella per contenere dati di qualsiasi genere, utilizzabile sulle personalizzazioni per conservare (ad es.) documenti crittografati.', ADD COLUMN `id_ref` INT(10) NULL COMMENT 'Referenza numerica alla fonte' AFTER `id`,	ADD INDEX `id_ref` (`id_ref`);
-- STOP_WHILE ( questo e' un tag che serve per istruire install.php a SMETTERE di eseguire le query su tutte le aziende dell'installazione )
