<?php

/*
  --------------------------------------------------------------------------
  GAzie - Gestione Azienda
  Copyright (C) 2004-2022 - Antonio De Vincentiis Montesilvano (PE)
  (http://www.devincentiis.it)
  <http://gazie.devincentiis.it>
  --------------------------------------------------------------------------
  Questo programma e` free software;   e` lecito redistribuirlo  e/o
  modificarlo secondo i  termini della Licenza Pubblica Generica GNU
  come e` pubblicata dalla Free Software Foundation; o la versione 2
  della licenza o (a propria scelta) una versione successiva.

  Questo programma  e` distribuito nella speranza  che sia utile, ma
  SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
  NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
  veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

  Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
  Generica GNU insieme a   questo programma; in caso  contrario,  si
  scriva   alla   Free  Software Foundation, 51 Franklin Street,
  Fifth Floor Boston, MA 02110-1335 USA Stati Uniti.
  --------------------------------------------------------------------------
 */

//*+- Nuovo stringa per colonna Fornitore in array 'Lista delle merci e dei servizi' - DC - 02 feb 2018

$strScript = array(
    "browse_document.php" =>
      array('title' => "Lista dei Documenti/Certificati",
        'errors' => array('Il formato del file non è stato accettato!',
        'Il file è troppo grande!',
        'Il file è vuoto!',
        'Nessun file selezionato'),
        'ins_this' => "Inserisci un Documento e/o Certificato",
        'upd_this' => "Modifica Documento e/o Certificato",
        'ins_this_img' => "Inserisci un'immagine",
        'upd_this_img' => "Modifica immagine",
        'item' => "Articolo di riferimento",
        'table_name_ref' => "Tabella di riferimento",
        'note' => "Didascalia/Appunti/Note",
        'ext' => "Estensione",
        'select' => "Sel.",
        'code' => "Codice"),
    "report_facility.php" =>
      array('title' => 'Lista deglle strutture ricettive',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto',
      ),
	 "report_extra.php" =>
      array('title' => 'Lista degli extra',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto',
      ),
    "report_accommodation.php" =>
      array('title' => 'Lista degli alloggi',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto',
      ),
    "report_booking.php" =>
      array("Elenco delle prenotazioni ",
        "codice",
		'number' => 'Numero prenotazione',
		'weekday_repeat' => 'settimanale',
		'status' => 'Stato',
		'print' => 'settimanale',
		'duplicate' => 'Duplica',
		'delete' => 'Cancella',
		'cancel' => 'Elimina',
		'submit' => 'Inserisci',
		'date' => 'data emissione',
		'title_value' => array('VPR' => 'Preventivi a clienti',
            'VOR' => 'Elenco prenotazioni',
            'VOW' => 'Elenco prenotazioni dal web',
            'VOG' => 'Prenotazioni settimanali del giorno'),
		'type' => 'Tipo',
        'type_value' => array('VPR' => 'Preventivo',
            'VOR' => 'Prenotazione',
            'VOW' => 'Prenotazione web',
            'VOG' => 'Prenotazione settimanale del giorno'),
		'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento di vendita:',
		'search' => 'Ricerca'
       ),
    "admin_movmag.php" =>
      array("movimento di magazzino ",
        "Data della registrazione ",
        "Causale ",
        "Cliente",
        "Fornitore",
        "C",
        "F",
        "Articolo",
        "Data documento ",
        "Descrizione doc.",
        "Sconto chiusura ",
        "Unit&agrave; di misura ",
        "Quantit&agrave; ",
        "Prezzo",
        "Sconto su rigo",
        "La data del documento non &egrave; corretta!",
        "La data di registrazione non &egrave; corretta!",
        "La data del documento &egrave; successiva a quella di registazione!",
        "Non &egrave; stato selezionato l'articolo!",
        "La quantit&agrave; non pu&ograve; essere uguale a zero!",
        "Questo movimento può essere modificato esclusivamente dal modulo Registro di campagna!",
        "Articolo con lotto",
        "Gli articoli composti possono essere caricati sono con una produzione!",
        "Si può caricare olio lampante da recupero solo se è sfuso!",
        "Non è stato indicato il recipiente di stoccaggio!",
        "Al consumatore finale si può vendere solo olio confezionato!",
        "Manca il codice operazione SIAN!",
        "La cessione omaggio è solo per olio confezionato!",
        "Lo scarico di morchie può avvenire solo da oli NON confezionati!",
        "Nello storno inventario bisogna indicare se carico o scarico",
        "L'inventario di magazzino deve essere un carico",
        "Non si può fare uno storno ad un inventario che non esiste",
        "Nel recipiente di stoccaggio selezionato non c'è sufficiente quantità",
        "La data di registrazione è precedente all'ultimo movimento inviato al SIAN. Se si conferma, questo movimento non sarà inviato al SIAN",
        "Quantità articolo non sufficiente! Se si conferma si creerà una quantità negativa",
        "La somma dei singoli lotti disponibili non corrisponde alla quantità inserita. Se la giacenza è corretta, allora, prima di inventariare, bisognerà aggiustare manualmente i lotti",
        "Non può uscire un lotto in data precedente alla sua creazione",
         'operat' => 'Operazione',
         'operat_value' => array(-1 => "Scarico", 0 => "Non opera", 1 => "Carico"),
        'cod_operaz_value' => array(11=>'',0=>'S0-Vendita olio a consumatore finale',6=>'S6-Cessione omaggio olio confezionato',7=>'S7-Scarico olio destinato ad altri usi',8=>'S8-Scarico olio autoconsumo',12=>'SP-Perdite o cali di olio',13=>'Q-Separazione morchie'),
        'cop_operazione' => 'Codice operazione SIAN',
        'cod_operaz_value_carico' => array(11=>'',10=>'C10-Carico olio lampante da recupero'),
        'partner' => 'Cliente/Fornitore',
        'del_this' => 'Elimina il movimento di magazzino',
        'amount' => " Valore in ",
        ),
    "report_caumag.php" =>
      array("causali di magazzino ",
        "Lista delle "
      ),
    "admin_catmer.php" =>
      array("categoria merceologica ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64Kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        "Descrizione estesa",
        "ID riferimento e-commerce",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)',
        'top' => 'Bottone su home ecommerce'
      ),
    "admin_ragstat.php" =>
      array("raggruppamento statistico ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)'
      ),
    "admin_caumag.php" =>
    array("causale di magazzino ",
        "Codice ",
        "Descrizione ",
        "Dati documento ",
        "Operazione",
        "Aggiorna Esistenza",
        "No",
        "Si",
        "Scarico",
        "Non opera",
        "Carico",
        "Cliente/Fornitore",
        "Cliente",
        "Entrambi",
        "Fornitore",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "il codice dev'essere un numero minore di 99"
      ),
    "genera_movmag.php" =>
      array("Genera movimenti di magazzino da documenti",
        "Data inizio ",
        "Data fine",
        "Azienda senza obbligo di magazzino fiscale!",
        " successiva alla ",
        "  righi sono da traferire in magazzino:",
        " Non ci sono righi da trasferire in magazzino!"),
    "select_giomag.php" =>
      array(0 => 'Stampa giornale di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa del giornale di magazzino',
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!'
        ),
        'date' => 'Data di stampa ',
        'date_ini' => 'Data registrazione inizio  ',
        'date_fin' => 'Data registrazione fine ',
        'mode' => 'Tipo di stampa sul pdf',
        'cover' => 'Stampa copertina',
        'subtitle' => 'Titolo aggiuntivo sul pdf (facoltativo)',
        'mode_value' => array(1 => 'Tutti i movimenti', 2 => 'Solo le entrate', 3 => 'Solo le uscite'),
        'price_value' => array(1 => 'con prezzi', 2 => 'senza prezzi con rag.sociale'),
        'header' => array('Data' => '', 'Causale' => '', 'Descrizione documento' => '' ,
          'Articolo' => '', 'Prezzo' => '', 'Importo' => '', 'UM' => '', 'Quantit&agrave;' => ''
          )
      ),
    "recalc_exist_value.php" =>
    array("Rivalutazione esistenza articoli da movimenti di magazzino",
        "Anno di riferimento",
        "Metodo di rivalutazione, scelto in configurazione azienda",
        "Sono stati movimentati i seguenti",
        "articoli durante il ",
        "Movimenti",
        "Codice",
        "Descrizione",
        "Esistenza",
        "UM acq.",
        "Valore precedente",
        "Valore rivalutato",
        "NON RIVALUTATO vedi nota ",
        "(1) perch&egrave; ci sono degli acquisti negli anni successivi al ",
        "(2) perch&egrave; non ci sono movimenti di acquisto nel ",
        "Non ci sono articoli movimentati!"),
    "inventory_stock.php" =>
    array('title' => "Inventario fisico di magazzino",
        'del' => "del",
        'catmer' => "Categoria Merceologica ",
        'select' => "Sel.",
        'code' => "Codice",
        'descri' => "Descrizione articolo",
        'mu' => "U.M.",
        'load' => "Carico",
        'unload' => "Scarico",
        'value' => "Nuovo valore giacenza",
        'v_a' => "Valore attuale",
        'v_r' => "Valore reale",
        'g_a' => "Giacenza attuale",
        'g_r' => "Giacenza reale",
        'g_v' => "Valore giacenza",
        'noitem' => "Non sono stati trovati articoli in questa categoria merceologica",
        'errors' => array(" La giacenza reale non pu&ograve; essere negativa",
        " Il valore reale non pu&ograve; essere negativo o uguale a zero",
        " Si st&agrave; tentando di fare l'inventario con giacenza attuale e reale entrambe a zero",
        " Per questo articolo è già stato fatto l'inventario nello stesso giorno"),
        'preview_title' => 'Confermando le scelte fatte si registreranno i seguenti movimenti di magazzino:'
    ),
    "select_schart.php" =>
      array(0 => 'Stampa schedari di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa delle schede di magazzino',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'date_ini' => 'Data registrazione inizio  ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'date_fin' => 'Data registrazione fine ',
        'header' => array('Data' => '', 'Causale' => '', 'Magazzino' => '', 'Descrizione<br \>documento' => '',
            'Prezzo' => '', 'UM' => '', 'Quantit&agrave;' => '',
            'Valore<br \>carico' => '', 'Valore<br \> scarico' => '',
            'Quantit&agrave;<br \>giacenza' => '', 'Valore<br \>giacenza' => ''
        ),
        'tot' => 'Consistenza'
      ),
    "stampa_schart.php" =>
      array(0 => 'SCHEDA DI MAGAZZINO dal ', 1 => ' al ',
        'bot' => 'a riportare : ',
        'top' => 'da riporto :  ',
        'item_head' => array('Codice', 'Cat.Merc', 'Descrizione', 'U.M.', 'ScortaMin.'),
        'header' => array('Data', 'Causale', 'Descrizione documento',
            'Prezzo', 'UM', 'Quantita',
            'Val. carico', 'Val. scarico',
            'Q.ta giacenza', 'Val. giacenza'
        ),
        'tot' => 'Consistenza al '
      ),
    "select_deplia.php" =>
      array('title' => 'Selezione per la stampa del catalogo',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'barcode' => 'Stampa',
        'jumpcat' => 'Cambio pagina al cambio categoria',
        'barcode_value' => array(0 => 'Immagini', 1 => 'Codici a Barre'),
        'listino' => 'Listino',
        'listino_value' => array(1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online')
      ),
    "select_listin.php" =>
      array('title' => 'Selezione per la stampa dei listini',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'listino' => 'Listino',
        'listino_value' => array(0 => 'd\'Acquisto', 1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online'),
        'id_anagra' => 'Fornitore (vuoto per tutti)',
        'ordineStampa' => 'Ordine di Stampa',
        'alternativeOrdineStampa' => array('default',
            'codice articolo',
            'descrizione articolo',
            'categoria articolo'
        ),
        'tipoStampa' => 'Tipo di Stampa',
        'alternativeTipoStampa' => array('espansa', 'compatta', 'verticale'),
      ),
    "admin_booking.php" =>
    array(array("VPR" => "Nuova prenotazione", "VOR" => "Prenotazione diretta", "VOW" => "Prenotazione dal Web", "VOG" => "Ordine settimanale del giorno"),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente'),
        'title' => 'Prenotazioni',
        " Prenotazione ",
        " piede ",
        " Tira su ",
        " Sezione ",
        " Indirizzo ",
        " Data ",
        " Listino ",
        " Pagamento ",
        " Banca ",
        " Destinazione ",
        " Causale ",
        " magazzino ",
        " vendita ",
        "Vettore",
        "Alloggio",
        "Quantit&agrave;",
        "Tipo",
        "Ricavo",
        "I.V.A.",
        "Codice",
        "Descrizione",
        "U.M.",
        "Prezzo",
        "Sconto",
        "Importo",
        "Imballo",
        "Spedizione",
        "Trasporto",
        "Porto",
        "Inizio trasporto",
        " ore ",
        "Imponibile",
        "Imposta",
        "Tot.Corpo",
        "Peso",
        "Totale",
        "Le date del check-in e/o check-out non sono corrette!",
        "La data del check-out non può essere precedente al check-in",
        "Non ci sono righi per poter emettere il documento!",
        "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
        "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
        "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!",
        "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
        "La data di emissione non &egrave; corretta!",
        "Non hai selezionato il cliente!",
        "Non hai selezionato la modalit&agrave; di pagamento!",
        "Un rigo &egrave; senza la descrizione!",
        "Un rigo &egrave; senza l'unit&agrave; di misura!",
        "Causale mag.",
        "Peso netto",
        "Peso lordo",
        "N.Colli",
        "Volume",
        "Provvigioni",
        "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
        "Questo documento &egrave; gi&agrave; stato contabilizzato!",
		"E stata superata la capienza massima di persone ammesse per l'alloggio",
		"Il numero di adulti è superiore a quello ammesso per l'alloggio",
		"Il numero di minori è superiore a quello ammesso per l'alloggio",
		"Prima di inserire un alloggio è necessario inserire le date di check-in e check-out",
		"ATTENZIONE OVERBOOKING! Il periodo inserito risulta occupato",
		"ATTENZIONE OVERBOOKING! Non c'è sufficiente disponibilità di questo extra",
        'speban' => "Spese incasso",
        'speban_title' => 'Spese incasso non documentate/rate',
        'traspo_title' => 'Spese trasporto non documentate',
        'stamp' => 'Bolli',
        'ritenuta' => 'Ritenuta ',
        'netpay' => 'Netto a pagare',
        'id_agente' => "Agente di vendita",
        'print_total' => "Stampa totale",
        'print_total_value' => array(0 => 'No', 1 => 'Si'),
        'delivery_time' => "Tempi di consegna",
        'day_of_validity' => "Giorni di validità ",
        'vat_constrain' => '(forza) IVA al ',
        'taxstamp' => 'Bollo',
        'virtual_taxstamp' => 'Modo',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Materiale', 2 => 'Virtuale'),
		'typerow_booking' => array(0 => 'Alloggio', 2 => 'Rigo descrittivo'),
        'weight' => 'peso',
        'zero_rows' => 'Il documento non contiene righi di alloggi, compila la ricerca alloggio nella sezione inserimento alloggio, inserisci il valore % per avere una lista completa o per effettuare una ricerca parziale',
        'discount_alert' => 'sconto da anagrafe articoli',
        'last_row' => 'Ultimo rigo inserito'
    ),
    "admin_house.php" =>
      array('title' => 'Gestione degli alloggi',
        'ins_this' => 'Inserimento alloggio',
        'upd_this' => 'Modifica l\'alloggio',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'movmag' => 'Si st&agrave; tentando di modificare il codice alloggio con dei movimenti di magazzino associati',
            'filmim' => 'Il file dev\'essere nel formato PNG, JPG, GIF',
            'filsiz' => 'L\'immagine non dev\'essere pi&ugrave; grande di 64Kb',
            'valcod' => 'Inserire un codice valido',
            'descri' => 'Inserire una descrizione',
            'unimis' => 'Inserire l\'unit&agrave; di misura delle vendite',
            'aliiva' => 'Inserire l\'aliquota I.V.A.',
            'lotmag' => 'Per avere la tracciabilità per lotti è necessario attivare la contabilità di magazzino in configurazione azienda',
            'no_ins' => 'Non sono riuscito ad inserire l\'alloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda ',
            'no_web' => 'Per attivare l\'alloggio nell\'e-commerce è necessario che sia inserito il riferimento ID e-commerce nella scheda magazzino'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
        ),
        'codice' => "Codice",
        'descri' => "Descrizione",
        'accommodation_type' => "Tipologia di alloggio",
        'accommodation_type_value' => array(3 => 'Appartamento', 4 => 'Casa indipendente', 5=> 'Bed & breakfast'),
        'body_text' => "Testo descrittivo",
        'lot_or_serial' => 'Lotti o numeri seriali',
        'lot_or_serial_value' => array(0 => 'No', 1 => 'Lotti', 2 => 'Seriale/Matricola'),
        'barcode' => "Codice a Barre EAN13",
        'image' => "Immagine (jpg,png,gif) max 64Kb",
        'unimis' => "Unit&agrave; di misura vendite",
        'quality' => "Qualità",
        'larghezza' => "Larghezza (mm)",
        'lunghezza' => "Lunghezza (mm)",
        'spessore' => "Spessore (mm)",
        'bending_moment'=>"Resistenza es.Wx cm³",
        'catmer' => "Categoria merceologica",
        'ragstat' => "Raggruppamento statistico",
        'preacq' => array( 0=>'Costo di produzione', 1=>'Prezzo d\'acquisto', 2=>'Costo di produzione' ),
        'preve1' => 'Prezzo di vendita listino 1',
        'preve2' => 'Prezzo di vendita listino 2',
        'preve3' => 'Prezzo di vendita listino 3',
        'preve4' => 'Prezzo di vendita listino 4',
        'preve1_sc' => 'Prezzo scontato 1',
        'preve2_sc' => 'Prezzo scontato 2',
        'preve3_sc' => 'Prezzo scontato 3',
        'preve4_sc' => 'Prezzo scontato 4',
        'sconto' => 'Sconto',
        'aliiva' => 'Aliquota IVA',
        'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
        'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
        'esiste' => 'Esistenza attuale',
        'valore' => 'Valore dell\'esistente',
        'last_cost' => 'Costo dell\'ultimo acquisto',
        'scorta' => 'Scorta minima',
        'riordino' => 'Lotto acquisto',
        'uniacq' => 'Unit&agrave; di misura acquisti',
        'classif_amb' => 'Classificazione ambientale',
        'classif_amb_value' => array(0=>'non classificato',1=>'irritante',2=>'nocivo',3=>'tossico',4=>'molto tossico'),
        'maintenance_period' => 'Periodicità manutenzione (gg)',
        'peso_specifico' => 'Peso specifico (kg/l) o Moltiplicatore',
        'volume_specifico' => 'Volume specifico',
        'pack_units' => 'Pezzi in imballo',
        'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
        'annota' => 'Annotazioni (pubblicate anche sul web)',
        'fornitori-codici' => 'Codici Fornitori',
        'document' => 'Documenti e/o certificazioni',
        'imageweb' => 'immagini e foto',
        'web_mu' => 'Unit&agrave; di misura online',
        'web_price' => 'Prezzo di vendita online',
        'web_multiplier' => 'Moltiplicatore prezzo web',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
        'ordinabile_value' => array( '' => '----','S' => 'Ordinare','N'=> 'Non ordinare'),
        'movimentabile' => 'Articolo Movimentabile',
        'movimentabile_value' => array ( '' => '----','S' => 'Si','N'=>'No','E' => 'Esaurito'),
        'codice_fornitore' => 'Codice del produttore',
        'utilizzato' => 'Utilizzato',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Casa inserita con successo clicca sulla X in alto a destra per uscire oppure...',
        'iterate_invitation' => 'INSERISCI UN\'ALTRA CASA',
        'browse_for_file' => 'Sfoglia',
        'id_anagra' => 'Fornitore di riferimento',
        'last_buys' => 'Ultimi acquisti da fornitori',
        'ordinabile' => 'Articolo ordinabile',
        'durability_mu' => 'Unità di misura durabilità',
        'durability' => 'Valore durabilità',
        'warranty_days' => 'Giorni di garanzia',
        'unita_durability' => array('' => '', '>' => '>', '<' => '<', 'H' => 'H', 'D' => 'D', 'M' => 'M'),
		'deposit_type_value' => array(0 => 'a valore', '1' => 'a percentuale sul totale'),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
        )
    ),
	"admin_facility.php" =>
    array('title' => 'Gestione delle strutture turistiche',
        'ins_this' => 'Inserimento struttura turistica',
        'upd_this' => 'Modifica la struttura turistica',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'empty_var' => 'Deve esserci per forza almeno un\'alloggio inserito nella struttura',
            'grcod' => 'Questo alloggio appartiene già ad un\'altra struttura',
            'descri' => 'Inserire una descrizione',
            'no_ins' => 'Non sono riuscito ad inserire l\'aalloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda per gli articoli ',
            'filmim' => 'Il file dev\'essere nel formato png, x-png, jpg, gif, x-gif, jpeg',
            'filetoobig' => 'Controllare che il file selezionato non superi le dimensioni impostate nella configurazione php'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
		),
		'info' => 'La struttura turistica è qui intesa come un insieme di alloggi presenti nello stesso stabile. <br/>Un esempio classico è un hotel che ha le camere nello stesso edificio.',
		'home' => "ID struttura",
		'variant' => "Alloggi",
		'codice' => "ID struttura",
        'descri' => "Descrizione",
		'image' => 'immagine',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'body_text' => 'Descrizione estesa',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Alloggio inserito con successo clicca sulla X in alto a destra per uscire oppure...',
        'mesg' => array(
        )
    ),
	"banner_search.php" =>
    array('title' => 'Iframe total search',       
        'err' => array(
			'date_uguali'=> 'check-in and check-out dates are identical',
			'start>end'=> 'Check-in date is after check-out date'
        ),
        'war' => array(
            'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
		'look'=>'Look at',
		'price'=>'Price',
		'search'=>"Search",
		'open_calendar'=>"Open total calendar",
		'imposta'=>"For availability and prices set check-in and check-out dates",
		'risultato'=>"Availability for the dates requested",
		'book'=>"Book",
		'nessun_risultato'=>"There is no availability for your requested dates. Try to modify them or look at the calendar."       
    ),
	"booking_form.php" =>
    array('title' => 'Booking form',
        'err' => array(
			'date_uguali'=> 'Check-in and check-out dates are the same',
			'start>end'=> 'Check-in date is after check-out date',
			'no_payment'=> 'You have to selecte a payment method',
			'no_ccinfo'=> 'Credit card datas are wrong or missing',
			'email-error' => 'The e-mail addresses you wrote are not the same',
			'email-validate' => 'The e-mail address is wrong'
        ),
        'war' => array(
            'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
		'rules_label'=>'Read the lease agreement',
		'privacy_label'=>'Read the privacy rules',
		'rules_button'=>'Lease agreement',
		'privacy_button'=>'Privacy rules',
		'title'=>'Booking form',
		'submit'=>'Go to summary',
		'return'=>'Back',
		'tur_tax' => 'Turist tax',
		'submitpay'=>'Sign the reservation and pay',
		'price_for' => 'Price for ',
		'discount_to' => 'Discount to be applied ',
		'select_guest' => 'Select the guests ',
		'max_capability' => 'Max capability ',
		'persons' => ' persons',
		'adults' => 'adults',
		'children' => 'children until 12 years old ',
		'price' => 'price',
		'each' => 'each',
		'per_person' => 'per person',
		'per_booking' => 'per booking',
		'per_night' => 'per night',
		'per_person_night' => 'per night and per each person',
		'out_stock' => 'Not available for this period',
		'quantity' => 'quantity',
		'per_stay' => 'per stay',
		'per_night_adult' => 'per night and only per adult',
		'per_person_adult' => 'per adult person',
		'required' => 'required',
		'read_rules' => 'I have read and I accept the lease',
		'read_privacy' => 'I accept the processing of sensitive data',
		'price_sum' => 'Prices summary',
		'booking_tot' => 'Total rental price',
		'which_deposit' => 'of which, for a confirmatory deposit',
		'select_pay_deposit' => 'Select the type of payment for the confirmation deposit',
		'bank_transfer' => 'Bank transfer',
		'credit_card_offline' => 'Credit card offline',
		'payment' => 'Payment',
		'transfer_instruction' => 'Make the bank transfer to the following coordinates within 24 hours',
		'bank_beneficiary' => 'Beneficiary',
		'amount' => 'Amount',
		'bank_reason' => 'Reason: Lease confirmation deposit ',
		'unsecure_protocol' => '> ATTENTION your connection is not secure, you are in http <',
		'secure_protocl' => 'You are in a secure connection https',
		'amount_pay' => 'Amount to pay',
		'nights' => 'nights',
		'name' => 'First name',
		'surname' => 'Surname',
		'address' => 'Address',
		'postalcode' => 'Postal code',
		'city' => 'City',
		'provincia' => 'District',
		'nation' => 'Nation',
		'vatcode' => 'Vat code',
		'phone' => 'Telephone',
		'email' => 'E-mail',
		'email2' => 'Just to avoid issue, repeat e-mail',
		'apartment' => 'Apartment',
		'house' => 'House',
		'bandb' => 'Bed & breakfast'
    ),
	
  "admin_extra.php" =>
    array('title' => 'Gestione degli extra',
		'ins_this' => 'Inserimento nuovo extra',
		'upd_this' => 'Aggiorna questo extra',
		'codice' => 'Codice extra',
		'descri' =>"Descrizione",
		'catmer' => 'Categoria merceologica',
		'body_text' => 'Descrizione estesa',
		'barcode' => 'Codice a barre',
		'image' => 'immagine base',
		'aliiva' => 'aliquota IVA',
		'web_url' => 'Url pagina web corrispondente',
		'web_public' => 'Pubblicazione sito web',
		'document' => 'Documenti e/o certificazioni',
		'imageweb' => 'immagini e foto HQ',
		'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'web_price' => 'Prezzo anche su web',
		'mod_prezzo' => 'Modalità applicazione prezzo',
		'web_multiplier' => 'Moltiplicatore prezzo web',
		'web_mu' => 'Unità di misura',
		'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
		'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
		'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
		'annota' => 'Annotazione',        
		'err' => array(		
        'valcod' => 'Non hai inserito il codice dell\'extra',  
		'descri' => 'Non hai scritto la descrizione'
		),
		" Extra ",
		"Descrizione",
		"Prezzo",
		"Modalità prezzo",
		"Codice alloggio",
		"5 booo",
		"codice extra",
		"codice alloggio",
		'typerow_price' => array(0 => 'a prenotazione', 1 => 'a persona', 2 => 'a notte', 3 => 'a persona e a notte', 4 => 'cadauno'),
		'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
      )
    )
);
?>
